{% set python_min = "3.10" %}
{% set version = "5.0.0" %}

package:
  name: pytest-redis
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pytest-redis/pytest_redis-{{ version }}.tar.gz
  sha256: 2eb0a1e5b63b34c9afcd117b3b728205fbe8d793706b2e9cb2152e81959da21f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}.*
    - uv-build >=0.12,<0.13
    - pip
  run:
    - python >={{ python_min }}
    - mirakuru >=2.6.0
    - packaging
    - port-for >=0.7.3
    - pytest >=8.4.0
    - redis-py >=5.0.1

test:
  imports:
    - pytest_redis
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}.*

about:
  home: https://pypi.org/project/pytest-redis/
  summary: Redis fixtures and fixture factories for Pytest.
  dev_url: https://github.com/dbfixtures/pytest-redis
  license: LGPL-3.0-only
  license_file: COPYING.lesser

extra:
  recipe-maintainers:
    - woutdenolf
