{% set name = "pytest-redis" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pytest_redis-{{ version }}.tar.gz
  sha256: f577be24f0d98fd4c3a81c2fa9fe59977cf394eca5b675758e369f430ffb8414

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0.0
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - pytest >=6.2
    - port-for >=0.6.0
    - mirakuru
    - redis-py >=3

test:
  imports:
    - pytest_redis
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ClearcodeHQ/pytest-redis
  summary: Redis fixtures and fixture factories for Pytest.
  dev_url: https://github.com/ClearcodeHQ/pytest-redis
  license: LGPL-3.0 AND GPL-3.0
  license_file:
    - COPYING.lesser
    - COPYING

extra:
  recipe-maintainers:
    - woutdenolf
